name: mobile_app
description: A Flutter mobile client for the Climate Monitoring System
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.6
  flutter_secure_storage: ^9.2.4
  provider: ^6.0.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

